# Generated by Django 4.2.14 on 2024-07-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('heure', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
        ),
    ]
